config/routes.rb
Rails.application.routes.draw do
  resources :domain_categories
  resources :forms do
    resources :formlines
  end
  resources :memos
  resources :links, except: %i[show]
  resources :survey_users
  resources :survey_groups
  resources :survey_answers
  resources :survey_options
  resources :surveys
  resources :instance_stories
  resources :instance_states
  resources :tickets
  resources :ticket_categories
  resources :ticket_statuses

  resources :pads_users
  resources :pads_groups
  resources :pads
  resources :visios
  resources :domains
  resources :users

  post 'domains/:id/users/:user_id', to: 'domains#update_user'
  get 'domains/:id/users/:user_id/edit', to: 'domains#edit_user', as: 'edit_domain_user'
  get 'domains/:id/users/new', to: 'domains#new_user', as: 'new_domain_user'
  post 'domains/:id/users', to: 'domains#create_user'
  delete 'domains/:id/users/:user_id', to: 'domains#delete_user', as: 'delete_domain_user'

  post 'memos/:id/archive', to: 'memos#archive', as: 'archive_memo'
  post 'visios/:id/archive', to: 'visios#archive', as: 'archive_visio'
  post 'pads/:id/archive', to: 'pads#archive', as: 'archive_pad'

  get 'users/:id/options' => 'users#options'
  post 'users/:id/options' => 'users#set_options'
  post 'users/:id/password' => 'users#set_password'

  get 'users/:id/groups' => 'users#groups'

  get '/visios_export', to: 'visios#export', as: 'visios_export'
  get '/pads_export', to: 'pads#export', as: 'pads_export'
  get '/memos_export', to: 'memos#export', as: 'memos_export'
  get '/surveys_export', to: 'surveys#export', as: 'surveys_export'
  get '/domains_export', to: 'domains#export', as: 'domains_export'
  get '/domains/:id/users_export', to: 'domains#users_export', as: 'domain_users_export'

  resources :config_modules do
    resources :instances
  end

  root 'services#index'
  resources :services, only: %i[index show]

  get 'users/:id/alias' => 'users#alias'
  delete '/alias/delete.json' => 'users#delete_alias'
  post '/alias/create.json' => 'users#create_alias'

  get 'domains/:id/administrators' => 'domains#administrators'

  get 'domains/:id/groups', to: 'groups#index', as: 'groups'
  post 'domains/:id/groups', to: 'groups#create'
  get 'domains/:id/groups/:group_id', to: 'groups#show', as: 'group'
  delete 'domains/:id/groups/:group_id', to: 'groups#destroy'
  patch 'domains/:id/groups/:group_id', to: 'groups#update', as: 'group_update'
  post 'login' => 'users#login'
  get 'logout' => 'users#logout', as: :logout

  get 'domains/:id/resources' => 'resources#index'
  post 'domains/:id/resources' => 'resources#create'
  delete 'domains/:id/resources' => 'resources#destroy'

  get 'domains/:id/infos' => 'domain_infos#index'
  get 'domains/:id/infos/:mod_id' => 'domain_infos#new'
  post 'domains/:id/infos/:mod_id' => 'domain_infos#create'

  get 'domains/:id/details' => 'domain_details#edit'
  post 'domains/:id/details' => 'domain_details#update'

  get 'visios' => 'visios#index'
  get 'visios/:id/users' => 'visios#users'
  get 'about' => 'about#index', as: 'about'
  get 'current_user' => 'users#current_user'
  post 'visios/:id/mails' => 'visios#mails'
  delete 'visios/:id/users' => 'visios#destroy_users'

  post '/visios_groups' => 'visios_groups#create'
  delete 'visios_groups/:id' => 'visios_groups#destroy'
  post '/visios_users' => 'visios_users#create'
  delete 'visios_users/:id' => 'visios_users#destroy'

  get '/visios/:id/button_to_bbb', to: 'visios#button_to_bbb', as: 'button_to_bbb'
  get '/visios/:id/recordings', to: 'visio_recordings#index', as: 'visio_recordings'
  get '/visios/:id/recordings_list', to: 'visio_recordings#visio_recordings', as: 'visio_recordings_list'
  get 'visios/:id/recordings/after_destroy', to: 'visio_recordings#after_destroy', as: 'visio_recordings_after_destroy'
  delete 'visios/:id/recordings/:record_id' => 'visio_recordings#destroy', as: 'visio_recordings_destroy'
  get '/visios/:id/settings', to: 'visio_settings#index', as: 'visio_settings'
  post '/visios/:id/settings', to: 'visio_settings#update_setting', as: 'visio_settings_update_setting'
  post '/visios/:id/settings/generate_viewer_access_code', to: 'visio_settings#generate_viewer_access_code',
                                                           as: 'visio_settings_generate_viewer_access_code'
  post '/visios/:id/settings/generate_moderator_access_code', to: 'visio_settings#generate_moderator_access_code',
                                                              as: 'visio_settings_generate_moderator_access_code'
  get 'visios/:id/recordings/:record_id/download', to: 'visio_recordings#download', as: 'visio_recording_download'

  post '/pads_groups' => 'pads_groups#create'
  delete 'pads_groups/:id' => 'pads_groups#destroy'

  post '/pads_users' => 'pads_users#create'
  delete 'pads_users/:id' => 'pads_users#destroy'

  get 'pads/:id/invitation' => 'pads#invitation'
  post 'pads/:id/mails' => 'pads#mails'
  post 'pads/:id/sharespad' => 'pads#sharespad'
  get 'pads/:id/users' => 'pads#users'
  delete 'pads/:id/users' => 'pads#destroy_users'

  post 'tickets/:id/new_message' => 'tickets#new_message'
  post 'surveys/:id/new_message' => 'surveys#new_message'
  get 'dates' => 'dates#index'
  get 'pads' => 'pads#show'
  get 'compta' => 'compta#index'
  get 'sympa' => 'sympa#index'

  get 'config_modules/:domain_id/infos' => 'config_modules#infos'

  get 'status' => 'events#index'
  get 'status/:id' => 'events#show', as: :show_instance_status
  get 'status/:id/events/:event_id' => 'events#messages', as: :show_instance_event
  post 'status/:id/events/:event_id' => 'events#new_message', as: :new_instance_event
  patch 'status/:id/events/:event_id' => 'events#update', as: :update_instance_event
  get 'status/:id/new' => 'events#new', as: :new_event
  post 'status/:id/new' => 'events#create', as: :create_instance_event

  post 'surveys/:id/share' => 'surveys#share'

  get 'statistics' => 'statistics#index'
  get 'statistics/instances' => 'statistics#instances'

  get '/invitations/:tag/:id', to: 'invitations#index', as: 'invitations'

  get 'forms/:id/formlines' => 'formlines#index'
  post '/forms/:id/formlines/new' => 'formlines#new'

  post '/invitations/:tag/:id/invite' => 'invitations#invite'
  get '/invitation/destroy/:type_id' => 'invitations#destroy'
  get '/invitation/send_email/:type_id' => 'invitations#share_invitation_to_email'
  get 'import' => 'import#launch_import'
  get 'end_visio', to: 'external_pages#end_visio', as: 'end_visio'
end

app/models/visio_recording.rb
# this is not a standard ActiveRecord model!
# it acts as an ActiveModel and the data is not stored. Data is fetched every time from BigBlueButton Greenlight.

class VisioRecording
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  attr_reader :id, :record_id, :name, :created_at, :recorded_at, :duration,
              :number_of_participants, :visibility, :formats

  def initialize(params = {})
    @id = params.fetch(:id, nil)
    @record_id = params.fetch(:record_id, nil)
    @name = params.fetch(:name, nil)
    @created_at = params.fetch(:created_at, nil).to_datetime
    @recorded_at = params.fetch(:recorded_at, nil).to_datetime
    @duration = params.fetch(:length, nil)
    @number_of_participants = params.fetch(:participants, nil)
    @visibility = params.fetch(:visibility, nil)
    @formats = params.fetch(:formats, nil)
  end
end

app/controllers/visio_recordings_controller.rb
class VisioRecordingsController < ApplicationController
  before_action do
    only_authorized_users('BigBlueButton')
  end
  before_action :set_url_local, only: %i[visio_recordings destroy download]
  before_action :set_visio, only: %i[index visio_recordings destroy after_destroy download]
  before_action :set_bbb_session, only: %i[visio_recordings destroy download]
  before_action only: %i[index destroy download] do
    only_owner!(@visio.owner_id, visios_path)
  end

  # GET /visios/1/recordings
  # GET /visios/1/recordings.json
  def index; end

  def visio_recordings
    unless @visio.owner_id == current_user.id
      redirect_to visios_path, notice: (I18n.t 'modules.bigbluebutton.authorizedaccesvisioconference')
    end
    redirect_to services_path, notice: (I18n.t 'modules.bigbluebutton.modulevisible').to_s unless @url_visios
    set_dataset
  end

  # Bidouille : Get affiché après un recording destroy pour éviter le rechargement en boucle infinie
  # de la page index des recordings
  def after_destroy; end

  # DELETE /visios/1/recordings/1
  # DELETE /visios/1/recordings/1.json
  def destroy
    if Core::BigBlueButton::Main.delete_room_recording(@sc, @session, params[:record_id])
      redirect_to visio_recordings_after_destroy_path(@visio),
                  notice: I18n.t('modules.bigbluebutton.successfuldestroyrecording')
    else
      redirect_to visio_recordings_after_destroy_path(@visio),
                  error: I18n.t('modules.bigbluebutton.cannotdeleterecording')
    end
  end

  def download
    set_dataset
    visio_recording = @dataset[:items].select { |recording| recording.record_id == params[:record_id] }.first
    redirect_to visio_recordings_path(@visio) && return unless visio_recording

    video_format = visio_recording.formats.select { |format| format[:recording_type] == 'video' }.first
    redirect_to visio_recordings_path(@visio) && return unless video_format

    video_url = "#{video_format[:url].gsub('/playback', '')}video-0.m4v"
    source = URI(video_url)
    Net::HTTP.start(source.host, source.port, use_ssl: true) do |http|
      req = Net::HTTP::Get.new source
      http.request(req) do |res|
        send_data res.read_body, filename: "#{@visio.name}.m4v", disposition: 'download'
      end
    end
  end

  private

  def set_dataset
    recordings = Core::BigBlueButton::Main.get_room_recordings(@sc, @session, @visio.friendly_id)
    recordings.map! { |recording| VisioRecording.new(recording.deep_symbolize_keys) }
    @dataset = dataset_pagination(recordings, index_params)
    @recordings_processing = Core::BigBlueButton::Main.get_room_recordings_processing(@sc, @session, @visio.friendly_id)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_visio
    @visio = Visio.find(params[:id])
  rescue StandardError => e
    flash.alert = "#{I18n.t('modules.bigbluebutton.dontexist')}|#{e}"
    redirect_to visios_path
  else
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def visio_params
    params.require(:visio).permit(:name, :comment, :date_start, :duration, :number_of_participants,
                                  :owner_id, :url_visios)
  end

  def set_url_local
    @config_module = ConfigModule.where(name: configmodule_name(Core::BigBlueButton)).first
    domaininfo = DomainInfo.where(config_module_id: @config_module.id,
                                  domain_id: current_user.domain.id).first
    @sc = ServiceContext.new(domaininfo, current_user.domain, current_user)
    @url_visios = Core::BigBlueButton::Main.get_login_url(@sc)
  end

  def set_bbb_session
    @session = Core::BigBlueButton::Main.get_session(@sc)
  end

  def index_params
    params.permit(:author, :order, :query, :page, :items_per_page, :archived)
  end
end

app/views/visio_recordings/_form.html.erb
<div class="flex justify-between m-10">
  <div class='hidden lg:flex'></div>
  <div class="w-full lg:w-1/2">
    <%= form_for(@visio) do |f| %>
      <% if @visio.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@visio.errors.count, "error") %> <%= I18n.t 'modules.bigbluebutton.error' %></h2>
          <ul>
            <% @visio.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="flex flex-col gap-2">
        <%= build_text_field(f, 'name', I18n.t('modules.bigbluebutton.salon'), 'video', required: true) %>
        <%= build_text_area(f, 'comment', 'align-left', placeholder: I18n.t('modules.bigbluebutton.comment'),) %>
        <%= build_datetime_field('visio', 'date_start', @visio.date_start, 'calendar', required: true) %>
        <%= build_number_field(f, 'duration', I18n.t('modules.bigbluebutton.duration_min'), 'clock', 1) %>
        <%= build_number_field(f, 'number_of_participants', I18n.t('modules.bigbluebutton.participant'), 'users', 2) %>
        <div class="flex flex-row justify-center gap-2">
          <%= button_tag I18n.t('modules.etherpad.valid'), 
          class: "rounded-lg bg-zourit-1 text-gray-100 hover:text-gray-100 hover:bg-gray-800 text-sm px-5 py-2" %>
          <%= link_to I18n.t('modules.etherpad.annuler') , visios_path,
          class: "rounded-lg bg-gray-100 text-gray-800 hover:text-gray-100 hover:bg-gray-800 text-sm px-5 py-2" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class='hidden lg:flex'></div>
</div>

app/views/visio_recordings/_visio_recording.html.erb
<tr id="<%= dom_id visio_recording %>" class="text-sm even:bg-gray-100 dark:even:bg-gray-900" x-data>
  <% date = visio_recording.created_at.strftime("%d/%m/%Y %H:%M %Z")%>
  <td class="pl-5 py-3 px-2">
  </td>
  <td class="text-gray-800 dark:text-gray-200 px-2 w-full sm:w-1/4">
    <%= visio_recording.recorded_at.in_time_zone('Paris').strftime('%d/%m/%Y %H:%M') %>
  </td>
  <td class="px-2 2xl:table-cell lg:whitespace-nowrap"><%= visio_recording.duration %></td>
  <td class="px-2 4xl:table-cell lg:whitespace-nowrap"><%= visio_recording.number_of_participants %></td>
  <td class="px-2 4xl:table-cell lg:whitespace-nowrap"><%= ts("modules.bigbluebutton.#{visio_recording.visibility.downcase}") %></td>
  <td class="px-2 4xl:table-cell lg:whitespace-nowrap">
    <div class="flex flex-row flex-nowrap mr-2 xl:mr-6 gap-1 border-z">
      <% for format in visio_recording.formats %>
        <% link = format[:recording_type] == 'video' ? format[:url].gsub('/playback', '') : format[:url] %>
        <a target='_blank' class="p-2 text-sm rounded-sm text-gray-200 hover:text-gray-100 bg-zourit-2 hover:bg-gray-500 transition transform ease-in-out duration-150" href="<%= link %>">
          <% if format[:recording_type] == 'video' 
            icon = 'video'
            video_link = link
          elsif format[:recording_type] == 'presentation'
            icon ='file-alt'
          else # Default icon in case the recording type is not recognized
            icon = 'question'
          end %>
          <div class='flex gap-1 items-center'>
            <i class="fas fa-<%= icon %>" title="<%= ts("modules.bigbluebutton.#{format[:recording_type]}") %>">
            </i>
            <span class='hidden md:flex'><%= format[:recording_type] %></span>
          </div>
        </a>
        <% if format[:recording_type] == 'video' %>
          <%= link_to visio_recording_download_path(@visio, visio_recording.record_id), 
                      title: ts('actions.download'), 
                      class: "p-2 text-sm rounded-sm text-gray-200 hover:text-gray-100 bg-zourit-2 hover:bg-gray-500 transition transform ease-in-out duration-150",
                      data: {turbo: false} do %>
            <%= fa_icon('file-download') %>
            <%= t('actions.download') %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </td>
  <td class="">
    <div class="flex flex-row flex-nowrap mr-2 ">
      <span @click="$clipboard('<%= video_link %>'); addFlashMessage('<%= t('actions.external_link_to_clipboard')%>')"
                    class="mr-2 rounded-lg text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm cursor-pointer"
                    title="<%= t('actions.copy_external_link_to_clipboard') %>">
        <%= fa_icon('clipboard ') %>
      </span>
      <%= link_to visio_recordings_destroy_path(record_id: visio_recording.record_id), 
        method: :delete,
        title: ts('modules.bigbluebutton.delete'), 
        class: "rounded-lg text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm", 
        data: { turbo_method: :delete,
                turbo_confirm: "#{ts 'modules.bigbluebutton.delete_recording_confirm'}",  
                turbo_frame: "_top" 
        } do %>
        <%= fa_icon('trash') %>
      <% end %>
    </div>
  </td>
</tr>

app/views/visio_recordings/after_destroy.html.erb
<%= render partial:'application/page_title', locals: {title: t('modules.bigbluebutton.visiorecordingslist'),
                                                      icon: icon('BigBlueButton'), back: { url: visio_recordings_path(@visio), title: t('actions.return') } } %>
<div class="flex text-left p-5 justify-center">
  <%= link_to 'Retour aux enregistrements', visio_recordings_path(@visio), class: 'p-2 bg-zourit-1 rounded-lg text-gray-200' %>
</div>

app/views/visio_recordings/index.html.erb
<%= render partial:'application/page_title', locals: {title: t('modules.bigbluebutton.visiorecordingslist'),
                                                      icon: icon('BigBlueButton'), back: { url: @visio, title: t('actions.return') } } %>
<div class="flow-root text-left p-5" 
  x-data="{ 
    refresh(page=1) { 
      $refs.pageInput.value=page; 
      $refs.searchForm.requestSubmit() 
    } 
  }">
  <%= form_with(
    url: visio_recordings_path, 
    method: :get, 
    class: "mb-0", 
    html: { "x-ref": "searchForm" }, 
    data: {
      turbo_frame: "visio_recordings", 
      turbo_action: "advance"
    }) do |form| %>
    <div>
      <%= turbo_frame_tag 'visio_recordings', src: visio_recordings_list_path(@visio), loading: :lazy, turbo_frame: "_top", class: 'flex flex-col w-full md:w-auto' do %>
        <div class='p-2 rounded-lg w-full text-center cursor-wait text-gray-800 dark:text-gray-200'>
          <%= ts('modules.bigbluebutton.loading_records')%><br/>
          <%= fa_icon('spinner', class: 'fa-pulse fa-3x') %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/visio_recordings/visio_recordings.html.erb
<%= turbo_frame_tag "visio_recordings" do %>
  <div class="overflow-x-auto inline-block min-w-full align-middle">
    <table class="min-w-full dark:text-gray-200">
      <thead>
        <tr class="whitespace-nowrap text-md text-left font-semibold text-gray-400 dark:text-gray-600 bg-gray-800 dark:bg-gray-200">
          <th class="py-5"></th>
          <th class="pr-3"><%= ts('modules.bigbluebutton.recordingdate') %></th>
          <th class="2xl:table-cell"><%= ts('modules.bigbluebutton.length') %></th>
          <th class="pl-2 4xl:table-cell"><%= ts('modules.bigbluebutton.numberofparticipants') %></th>
          <th class="pl-2 4xl:table-cell"><%= ts('modules.bigbluebutton.visibility') %></th>
          <th class="pl-2 4xl:table-cell"><%= ts('modules.bigbluebutton.formats') %></th>
          <th class=""></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
        <%= render @dataset[:items] %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan=7 class='text-center'>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
  <% if @recordings_processing > 0 %>
    <div class="flex flex-col text-center py-8 dark:text-gray-200">
      <%= fa_icon('hourglass-half', size: '4x', class: 'pb-2') %>
      <%= ts("modules.bigbluebutton.processingrecording") %>
    </div>
  <% elsif @dataset[:count] == 0 %>
    <div class="flex flex-col text-center py-8 dark:text-gray-200">
      <%= fa_icon('ban', size: '4x', class: 'pb-2') %>
      <%= t('shared.no_results_found') %>
    </div>
  <% end %>
<% end %>