config/routes.rb
Rails.application.routes.draw do
  resources :domain_categories
  resources :forms do
    resources :formlines
  end
  resources :memos
  resources :links, except: %i[show]
  resources :survey_users
  resources :survey_groups
  resources :survey_answers
  resources :survey_options
  resources :surveys
  resources :instance_stories
  resources :instance_states
  resources :tickets
  resources :ticket_categories
  resources :ticket_statuses

  resources :pads_users
  resources :pads_groups
  resources :pads
  resources :visios
  resources :domains
  resources :users

  post 'domains/:id/users/:user_id', to: 'domains#update_user'
  get 'domains/:id/users/:user_id/edit', to: 'domains#edit_user', as: 'edit_domain_user'
  get 'domains/:id/users/new', to: 'domains#new_user', as: 'new_domain_user'
  post 'domains/:id/users', to: 'domains#create_user'
  delete 'domains/:id/users/:user_id', to: 'domains#delete_user', as: 'delete_domain_user'

  post 'memos/:id/archive', to: 'memos#archive', as: 'archive_memo'
  post 'visios/:id/archive', to: 'visios#archive', as: 'archive_visio'
  post 'pads/:id/archive', to: 'pads#archive', as: 'archive_pad'

  get 'users/:id/options' => 'users#options'
  post 'users/:id/options' => 'users#set_options'
  post 'users/:id/password' => 'users#set_password'

  get 'users/:id/groups' => 'users#groups'

  get '/visios_export', to: 'visios#export', as: 'visios_export'
  get '/pads_export', to: 'pads#export', as: 'pads_export'
  get '/memos_export', to: 'memos#export', as: 'memos_export'
  get '/surveys_export', to: 'surveys#export', as: 'surveys_export'
  get '/domains_export', to: 'domains#export', as: 'domains_export'
  get '/domains/:id/users_export', to: 'domains#users_export', as: 'domain_users_export'

  resources :config_modules do
    resources :instances
  end

  root 'services#index'
  resources :services, only: %i[index show]

  get 'users/:id/alias' => 'users#alias'
  delete '/alias/delete.json' => 'users#delete_alias'
  post '/alias/create.json' => 'users#create_alias'

  get 'domains/:id/administrators' => 'domains#administrators'

  get 'domains/:id/groups', to: 'groups#index', as: 'groups'
  post 'domains/:id/groups', to: 'groups#create'
  get 'domains/:id/groups/:group_id', to: 'groups#show', as: 'group'
  delete 'domains/:id/groups/:group_id', to: 'groups#destroy'
  patch 'domains/:id/groups/:group_id', to: 'groups#update', as: 'group_update'
  post 'login' => 'users#login'
  get 'logout' => 'users#logout', as: :logout

  get 'domains/:id/resources' => 'resources#index'
  post 'domains/:id/resources' => 'resources#create'
  delete 'domains/:id/resources' => 'resources#destroy'

  get 'domains/:id/infos' => 'domain_infos#index'
  get 'domains/:id/infos/:mod_id' => 'domain_infos#new'
  post 'domains/:id/infos/:mod_id' => 'domain_infos#create'

  get 'domains/:id/details' => 'domain_details#edit'
  post 'domains/:id/details' => 'domain_details#update'

  get 'visios' => 'visios#index'
  get 'visios/:id/users' => 'visios#users'
  get 'about' => 'about#index', as: 'about'
  get 'current_user' => 'users#current_user'
  post 'visios/:id/mails' => 'visios#mails'
  delete 'visios/:id/users' => 'visios#destroy_users'

  post '/visios_groups' => 'visios_groups#create'
  delete 'visios_groups/:id' => 'visios_groups#destroy'
  post '/visios_users' => 'visios_users#create'
  delete 'visios_users/:id' => 'visios_users#destroy'

  get '/visios/:id/button_to_bbb', to: 'visios#button_to_bbb', as: 'button_to_bbb'
  get '/visios/:id/recordings', to: 'visio_recordings#index', as: 'visio_recordings'
  get '/visios/:id/recordings_list', to: 'visio_recordings#visio_recordings', as: 'visio_recordings_list'
  get 'visios/:id/recordings/after_destroy', to: 'visio_recordings#after_destroy', as: 'visio_recordings_after_destroy'
  delete 'visios/:id/recordings/:record_id' => 'visio_recordings#destroy', as: 'visio_recordings_destroy'
  get '/visios/:id/settings', to: 'visio_settings#index', as: 'visio_settings'
  post '/visios/:id/settings', to: 'visio_settings#update_setting', as: 'visio_settings_update_setting'
  post '/visios/:id/settings/generate_viewer_access_code', to: 'visio_settings#generate_viewer_access_code',
                                                           as: 'visio_settings_generate_viewer_access_code'
  post '/visios/:id/settings/generate_moderator_access_code', to: 'visio_settings#generate_moderator_access_code',
                                                              as: 'visio_settings_generate_moderator_access_code'
  get 'visios/:id/recordings/:record_id/download', to: 'visio_recordings#download', as: 'visio_recording_download'

  post '/pads_groups' => 'pads_groups#create'
  delete 'pads_groups/:id' => 'pads_groups#destroy'

  post '/pads_users' => 'pads_users#create'
  delete 'pads_users/:id' => 'pads_users#destroy'

  get 'pads/:id/invitation' => 'pads#invitation'
  post 'pads/:id/mails' => 'pads#mails'
  post 'pads/:id/sharespad' => 'pads#sharespad'
  get 'pads/:id/users' => 'pads#users'
  delete 'pads/:id/users' => 'pads#destroy_users'

  post 'tickets/:id/new_message' => 'tickets#new_message'
  post 'surveys/:id/new_message' => 'surveys#new_message'
  get 'dates' => 'dates#index'
  get 'pads' => 'pads#show'
  get 'compta' => 'compta#index'
  get 'sympa' => 'sympa#index'

  get 'config_modules/:domain_id/infos' => 'config_modules#infos'

  get 'status' => 'events#index'
  get 'status/:id' => 'events#show', as: :show_instance_status
  get 'status/:id/events/:event_id' => 'events#messages', as: :show_instance_event
  post 'status/:id/events/:event_id' => 'events#new_message', as: :new_instance_event
  patch 'status/:id/events/:event_id' => 'events#update', as: :update_instance_event
  get 'status/:id/new' => 'events#new', as: :new_event
  post 'status/:id/new' => 'events#create', as: :create_instance_event

  post 'surveys/:id/share' => 'surveys#share'

  get 'statistics' => 'statistics#index'
  get 'statistics/instances' => 'statistics#instances'

  get '/invitations/:tag/:id', to: 'invitations#index', as: 'invitations'

  get 'forms/:id/formlines' => 'formlines#index'
  post '/forms/:id/formlines/new' => 'formlines#new'

  post '/invitations/:tag/:id/invite' => 'invitations#invite'
  get '/invitation/destroy/:type_id' => 'invitations#destroy'
  get '/invitation/send_email/:type_id' => 'invitations#share_invitation_to_email'
  get 'import' => 'import#launch_import'
  get 'end_visio', to: 'external_pages#end_visio', as: 'end_visio'
end

app/models/domain.rb
# frozen_string_literal: true

class Domain
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include DomainsHelper
  include UsersHelper
  include GroupsHelper
  include SemanticLogger::Loggable

  attr_accessor :name, :zouritDomainQuota, :zouritAttributedQuota,
                :zouritQuotaLeft, :nbUsersDomain, :details
  attr_reader :id

  def initialize(name = nil, id = nil, zouritDomainQuota = 0, zouritAttributedQuota = 0, nbUsersDomain = 0)
    self.name = name
    @id = id
    self.zouritDomainQuota = zouritDomainQuota
    self.zouritAttributedQuota = zouritAttributedQuota
    self.nbUsersDomain = nbUsersDomain
    self.details = DomainDetail.new
  end

  def persisted?
    false
  end

  def self.find(opts)
    domain = UUID.validate(opts) ? find_domain_by_uuid(opts) : find_domain_by_name(opts)
    domain&.details = DomainDetail.where(domain_id: domain.id).first
    domain
  end

  def self.all(with_quota = true)
    list_domains with_quota
  end

  def administrators
    get_administrators name
  end

  def save
    if @id
      # FIXME: ici il s'agit de la modification d'un domaine, j'ai l'impression qu'on ne passe jamais par ici !!!
      update_domain(name, zouritdomainquota: zouritDomainQuota)
    else # create domain
      create_domain name, zouritDomainQuota
      @id = Domain.find(name).id
      details.domain_id = @id
    end
    details.save
  rescue LdapError => e
    logger.error('unable to create domain', e)
    false
  end

  # Suppression du domaine
  def destroy
    logger.info("Suppression des utilisateurs du domaine <#{name}>...")
    list_users(name).each(&:destroy)

    logger.info("Suppresion des groupes du domaine <#{name}>...")
    list_groups(name, false, true).each(&:destroy)

    logger.info("Suppression du domaine <#{name}> pour chaque module...")
    success = true
    DomainInfo.where(domain_id: id).each do |di|
      module_name = di.config_module.name
      success &&= eval("Core::#{module_name}::Main.destroy_domain di, self")
    end

    logger.info("Suppression finale du domaine <#{name}>")
    # TODO: à vérifier si la ligne ci-dessous s'exécute bien... suspiscion de bug ici
    success &&= DomainInfo.where(domain_id: id).destroy_all
    success &&= details.destroy

    success ? destroy_domain(name) : false
  end

  # Calcul du quota déjà attribué
  def set_attributed_quota
    self.zouritAttributedQuota = attributed_quotas
    self.zouritQuotaLeft = zouritDomainQuota - zouritAttributedQuota
  end

  def set_nb_users
    self.nbUsersDomain = users.count
  end

  def attributed_quotas_excepted_users(excepted_user_id)
    meta_options_ids = MetaOption.where(field: 'user',
                                        field_type: 'Quota',
                                        config_module_id: config_modules.map(&:id))
    users_ids = users.map(&:id)
    users_ids = users_ids.excluding(excepted_user_id) if excepted_user_id
    UserOption.where(meta_option_id: meta_options_ids, user_id: users_ids).map do |uo|
      uo.value.to_i
    end.reduce(0, :+)
  end

  def attributed_quotas
    meta_options_ids = MetaOption.where(field: 'user',
                                        field_type: 'Quota',
                                        config_module_id: config_modules.map(&:id))
    UserOption.where(meta_option_id: meta_options_ids, domain_id: id).map do |uo|
      uo.value.to_i
    end.reduce(0, :+)
  end

  def self.all_attributed_quota
    meta_options_ids = MetaOption.where(field: 'user',
                                        field_type: 'Quota')
    UserOption.where(meta_option_id: meta_options_ids).map do |uo|
      uo.value.to_i
    end.reduce(0, :+)
  end

  def get_domain_info(module_name)
    mod = ConfigModule.where(name: module_name).first
    DomainInfo.where(domain_id: id, config_module_id: mod.id).first
  end

  def get_module_instance(module_name)
    di = get_domain_info(module_name)
    di ? di.instance : false
  end

  def domain_infos
    DomainInfo.where(domain_id: id)
  end

  def instances
    DomainInfo.where(domain_id: id).map(&:instance)
  end

  def config_modules
    DomainInfo.where(domain_id: id).map(&:config_module).sort { |a, b| a.order <=> b.order }
  end

  def users
    User.list_from_domain(self)
  end

  def groups(with_users: false, with_tous: false)
    list_groups(name, with_users, with_tous)
  end

  def full_name
    details.full_name || name
  end

  def address
    details.address
  end

  def phone
    details.phone
  end

  def email
    details.email
  end

  def admin_lastname; end
  def admin_firstname; end
  def admin_email; end
  def admin_password; end
  def admin_password_confirmation; end

  private

  def get_binding(object)
    binding
  end
end

app/helpers/domains_helper.rb
# FIXME: à déplacer dans lib/... OU models/. ces méthodes ne devraient pas être situées ici car elles sont accessibles depuis les vues!
module DomainsHelper
  class LdapError < StandardError
  end

  LDAP_BASE = YAML.load_file(Rails.root.join('config', 'ldap.yml'))['base']

  def self.included(base)
    base.extend(ClassMethods)
  end

  def domain_from_mail(mail)
    self.class.domain_from_mail mail
  end

  def list_domains(with_quota = true)
    self.class.list_domains(with_quota)
  end

  def export_all_domains
    domains = ''
    list_domains.each do |domain|
      list_users(domain.name).each do |user|
        domains += "#{domain.name}, #{domain.zouritDomainQuota}, #{user.id}, #{user.email}, #{user.zouritZimbraQuota}, #{user.zouritCloudQuota}\n"
      end
    end
    logger.info domains
  end

  def get_administrators(domain)
    base = "ou=people,o=#{domain},#{LDAP_BASE}"
    filter = Net::LDAP::Filter.eq('zouritAdmin', 'TRUE')
    attributes = %w[db entryuuid sn cn displayname mail objectclass]
    results = SUPERLDAP.search(base:, filter:, attributes:)
    admins = []
    results.each do |r|
      admins << User.new(id: r.entryuuid.first,
                         dn: r.dn,
                         first_name: r.cn.first,
                         last_name: r.sn.first,
                         email: r.mail.first,
                         admin: true,
                         zouritZimbraEmail: r.objectclass.include?('zouritZimbraEmail'),
                         zouritZimbraContact: r.objectclass.include?('zouritZimbraContact'),
                         zouritZimbraCalendar: r.objectclass.include?('zouritZimbraCalendar'),
                         zouritZimbraTask: r.objectclass.include?('zouritZimbraTask'))
    end
    admins
  end

  def create_domain(name, zouritDomainQuota)
    logger.info("création du domaine <#{name}> avec quota <#{zouritDomainQuota} Go> ...")
    dn = "o=#{name},#{LDAP_BASE}"
    attr = {
      o: name,
      objectclass: %w[top organization zouritDomain],
      zouritdomainquota: zouritDomainQuota.to_s
    }
    ldap_add_or_fail(dn, attr, 'error domain creation')

    people_dn = 'ou=people,' + dn
    attr = {
      ou: 'people',
      objectclass: %w[top organizationalUnit]
    }
    ldap_add_or_fail(people_dn, attr, 'error people object creation under domain')

    group_dn = 'ou=groups,' + dn
    attr = {
      ou: 'groups',
      objectclass: %w[top organizationalUnit]
    }
    ldap_add_or_fail(group_dn, attr, 'error groups object creation under domain')
    logger.info("création du domaine <#{name}> avec quota <#{zouritDomainQuota} Go> ... SUCCESS")
  end

  def update_domain(domain, replace = {}, add = {}, delete = {})
    dn = "o=#{domain},#{LDAP_BASE}"
    args = []
    replace.each do |key, value|
      args << [:replace, key, value]
    end
    add.each do |key, value|
      args << [:add, key, value]
    end
    delete.each do |key, value|
      args << [:delete, key, value]
    end
    if SUPERLDAP.modify dn:, operations: args
      true
    else
      puts "error domain update : #{SUPERLDAP.get_operation_result.message} : #{args}"
      false
    end
  end

  def destroy_domain(name)
    dn = "o=#{name},#{LDAP_BASE}"
    people = 'ou=people,' + dn
    SUPERLDAP.delete(dn: people)
    groups = 'ou=groups,' + dn
    SUPERLDAP.delete(dn: groups)
    SUPERLDAP.delete(dn:)
  end

  def find_domain_by_name(name)
    find_domain_by_name name
  end

  module ClassMethods
    def find_domain_by_uuid(uuid)
      base = LDAP_BASE
      filter = Net::LDAP::Filter.eq('entryuuid', uuid)
      find_domain base, filter
    end

    def find_domain_by_name(name)
      base = LDAP_BASE
      dn = "o=#{name},#{base}"
      filter = Net::LDAP::Filter.eq('entrydn', dn)
      find_domain base, filter
    end

    def find_domain(base, filter, with_quota = true)
      attributes = with_quota ? %w[o entryuuid zouritDomainQuota] : %w[o entryuuid]
      response = SUPERLDAP.search(base:, filter:, attributes:).first
      domain = nil
      if response
        quota = (begin
          response.zouritdomainquota.first.to_i
        rescue StandardError
          0
        end)
        domain = Domain.new(response.o.first, response.entryuuid.first, quota)
      end
      domain
    end
  end

  private

  def ldap_add_or_fail(dn, attr, message)
    return if SUPERLDAP.add(dn:, attributes: attr)

    raise LdapError, "#{message} : #{SUPERLDAP.get_operation_result.message} : #{dn} #{attr}"
  end

  module ClassMethods
    def list_domains(with_quota = true)
      base = LDAP_BASE
      filter = Net::LDAP::Filter.eq('o', '*')
      attributes = with_quota ? %w[o entryuuid zouritDomainQuota] : %w[o entryuuid]
      result = SUPERLDAP.search(base:, filter:, attributes:)
      domains = []
      logger = SemanticLogger['DomainsHelper::ClassMethods']
      result.each do |r|
        next if r.dn == LDAP_BASE

        d = nil
        if with_quota
          # logger.info("#{r.o.first} with quota:#{r.zouritdomainquota.first}Go")
          d = Domain.new(r.o.first,
                         r.entryuuid&.first,
                         (begin
                           r.zouritdomainquota.first.to_i
                         rescue StandardError
                           0
                         end))
          d.set_attributed_quota
        else
          logger.info("#{r.o.first} no quota")
          d = Domain.new(r.o.first, r.entryuuid)
        end
        d.details = DomainDetail.where(domain_id: d.id).first_or_create
        domains << d
      end
      domains
    end
  end
end

app/views/domains/_dialog_delete_domain.html.erb
<dialog
  class="fixed rounded-lg w-full sm:w-8/12 xl:w-4/12 backdrop:bg-zourit-2 backdrop:opacity-50 open:animate-fade-in"
  x-ref='dialogDeleteDomain'>
  <div class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
    <div class="sm:flex sm:items-start">
      <div class="p-8 mx-auto flex flex-shrink-0 items-center justify-center rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
        <%= fa_icon('exclamation-triangle', size: '2x', class: 'text-red-700') %>
      </div>
      <div class="mt-3 text-center sm:ml-4 sm:mt-0 sm:text-left">
        <h2 class="text-2xl font-semibold leading-6 text-gray-900" x-text="domainName"></h2>
        <h3 class="text-base font-semibold leading-6 text-gray-900"><%= ts('domains.index.delete_title') %></h3>
        <div class="mt-2">
          <p class="text-sm text-gray-500"><%= ts('domains.index.warning_delete') %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
    <%= link_to ts('domains.index.delete_domain_confirm'), 
                nil, 
                method: :delete, 
                'x-ref': 'deleteButton',
                data: { "turbo-method": :delete, turbo_confirm: "#{ts 'domains.index.confirm_delete'}" },
                class: "inline-flex w-full justify-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold 
                        text-white shadow-sm hover:bg-red-500 sm:ml-3 sm:w-auto", 
                title: ts(:delete_domain) %>
    <button type="button" 
            @click='$refs.dialogDeleteDomain.close()' 
            class="mt-3 inline-flex w-full justify-center rounded-md bg-white 
                   px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 
                   ring-inset ring-gray-300 hover:bg-gray-50 sm:mt-0 sm:w-auto">
      <%= ts('actions.cancel') %>
    </button>
  </div>
</dialog>

app/views/domains/_domain.html.erb
<tr id="<%= dom_id domain %>" class="text-sm even:bg-gray-100 dark:even:bg-gray-900 dark:text-gray-200">
  <td class="px-2 w-1/4">
    <%= domain.full_name %>
  </td>
  <td class="px-2 w-full lg:w-1/4">
    <%= domain.name %>
  </td>
  <td class="px-2 hidden lg:table-cell w-full">
    <%= domain.details.domain_category&.category %>
  </td>
  <td class="pr-4 hidden md:table-cell lg:whitespace-nowrap">

    <% percent = domain.zouritDomainQuota.positive? ? (domain.zouritAttributedQuota*100/domain.zouritDomainQuota).round(0) : 100 %>

    <% overquota = percent>100 %>

    <% percent = 100 if overquota %>

    <div class='flex flex-row gap-1'>
      <div class="w-24 lg:w-48 bg-neutral-200 dark:bg-gray-200 shadow-inner rounded-md">
        <div class="bg-zourit-1 h-6 p-0.5 text-center text-xs font-medium leading-none text-gray-900 whitespace-nowrap py-2 rounded-md"
           style="width: <%= percent %>%">
        </div>
      </div>

      <span class="text-xs pt-1 <%= overquota ? 'text-red-800' : 'text-gray-800' %> dark:text-white"><%= "#{domain.zouritAttributedQuota}/#{domain.zouritDomainQuota}Go" %></span>
    </div>
  </td>
  <td class="">
    <div class="flex flex-row flex-nowrap mr-2 ">
      <%= link_to "/domains/#{domain.id}/details", title: ts('domains.index.informations'), class: "rounded-l-lg text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm", data: { turbo: false } do %>
        <%= fa_icon 'file-alt' %>
      <% end %>
      <%= link_to "/domains/#{domain.id}/infos", title: ts('domains.index.parameters'), class: "text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm", data: { turbo: false } do %>
        <%= fa_icon 'cog' %>
      <% end %>
      <%= link_to domain_path(domain.id), title: ts('domains.index.users'), class: "mr-2 rounded-r-lg text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-smg", data: { turbo: false } do %>
        <%= fa_icon 'users' %>
      <% end %>
      <span title="<%=ts('domains.index.delete_domain')%>" 
            @click="showDeleteDialog('<%= domain.name %>', '<%= domain_path(domain.id) %>')"
            class="cursor-pointer rounded-lg text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm">
        <%= fa_icon('trash') %>
      </span>
    </div>
  </td>
</tr>

app/views/domains/_domains.html.erb
<%= turbo_frame_tag "domains", target: "_top" do %>
  <div class="inline-block min-w-full align-middle pt-2">
    <table class="min-w-full divide-y divide-gray-300">
      <thead>
        <tr class="whitespace-nowrap text-md text-left font-semibold text-gray-400 bg-gray-800 dark:bg-gray-200 dark:text-gray-600">
          <th scope="col" class="py-3 pl-3"><%= build_th_order('full_name', ts('domains.index.structure'), params[:order]) %></th>
          <th scope="col" class="pr-3"><%= build_th_order('name', ts('domains.index.domain'), params[:order]) %></th>
          <th scope="col" class="pr-2 hidden lg:table-cell"><%= ts('domain_categories.index.category') %></th>
          <th scope="col" class="pr-2 hidden md:table-cell"><%= ts('domains.index.attributed_quota') %></th>
          <th scope="col" class=""></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
        <%= render @dataset[:items] %>
      </tbody>
    </table>
  </div>
  <div class="text-sm text-gray-500 mt-5">
    <%= render "application/pagination", dataset: @dataset do %>
      <%= link_to domains_export_path(author: params[:author], 
                                      order: params[:order], 
                                      query: params[:query], 
                                      page: 1, 
                                      items_per_page: @dataset[:count], 
                                      archived: params[:archived]),
                                      class: "ml-2 rounded-lg bg-zourit-1 hover:bg-gray-800 !text-gray-100 hover:text-gray-100 text-lg p-2", title: "Tout exporter" do %>
        <%= fa_icon('download') %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/domains/show.html.erb
<%= render partial:'application/page_title', 
           locals: {title: t('domain.userdomainmanage'), 
                    domain: @domain.name,
                    icon: 'globe'} %>
<div x-data="{ 
    domainName: '',
    refresh(page=1) { 
      $refs.pageInput.value=page; 
      $refs.searchForm.requestSubmit();
    }, 
    showDeleteDialog(domain_name, url) {
      this.domainName = domain_name;
      $refs.deleteButton.href = url;
      $refs.dialogDeleteDomain.showModal();
    }
  }" >
  <div class="flow-root text-left p-5">
    <%= form_with(url: domain_path, 
                  method: :get, 
                  class: "mb-0", 
                  html: { "x-ref": "searchForm" }, 
                  data: {
                    turbo_frame: "users", 
                    turbo_action: "advance"
                  }) do |form| %>
      <div class="flex flex-col xl:flex-row justify-between gap-2">
        <div class="flex gap-2">
          <%= build_button(text: ts(:new_user), link: new_domain_user_path(@domain.id), icon: 'plus') %>
          <%= build_button(text: ts('domain.groupmanage'), link: "/domains/#{@domain.id}/groups", icon: 'users') %>
          <%= build_button(text: ts('domain.domainoption'), icon: 'chart-area', click: "document.getElementById('dialogStatDomain').showModal(); showGraphModale_stat()") %>
        </div>
        <div class="flex flex-col md:flex-row gap-2">
          <div class="flex flex-row">
            <%= button_tag id: "submit-button", class: "h-auto rounded-l-lg bg-zourit-1 hover:bg-gray-800 !text-gray-100 hover:text-gray-100 text-lg p-2" do %>
              <%= fa_icon('search') %>
            <% end %>
            <%= form.text_field :query, "@input.debounce": "refresh()", class: "bg-gray-800 dark:bg-gray-200 border border-gray-800 text-gray-100 dark:text-gray-800 text-sm rounded-r-lg w-full pl-5 p-2 focus:border-zourit-1 focus:ring-1 focus:ring-zourit-1", placeholder: "Rechercher" %>
            <!-- Ces input hidden sont modifié via alpinejs -->
            <%= form.text_field :order, 'x-ref': 'orderInput', class:"hidden" %>
            <%= form.text_field :page, 'x-ref': 'pageInput', class:"hidden" %>
            <div class="flex ml-1 items-center">
              <%= build_toggle_field(
                  form, 
                  'admin', 
                  t(:admin), 
                  checked: params[:admin] == 'true', 
                  "on_change": "refresh()") %>

            </div>

          </div>
        </div>
      </div>
      <div class="">
        <%= render "users/users", users: @domain.users %>
      </div>
    <% end %>
  </div>
  <%= render 'dialog_domain_statistics' %>
</div>