config/routes.rb
Rails.application.routes.draw do
  resources :domain_categories
  resources :forms do
    resources :formlines
  end
  resources :memos
  resources :links, except: %i[show]
  resources :survey_users
  resources :survey_groups
  resources :survey_answers
  resources :survey_options
  resources :surveys
  resources :instance_stories
  resources :instance_states
  resources :tickets
  resources :ticket_categories
  resources :ticket_statuses

  resources :pads_users
  resources :pads_groups
  resources :pads
  resources :visios
  resources :domains
  resources :users

  post 'domains/:id/users/:user_id', to: 'domains#update_user'
  get 'domains/:id/users/:user_id/edit', to: 'domains#edit_user', as: 'edit_domain_user'
  get 'domains/:id/users/new', to: 'domains#new_user', as: 'new_domain_user'
  post 'domains/:id/users', to: 'domains#create_user'
  delete 'domains/:id/users/:user_id', to: 'domains#delete_user', as: 'delete_domain_user'

  post 'memos/:id/archive', to: 'memos#archive', as: 'archive_memo'
  post 'visios/:id/archive', to: 'visios#archive', as: 'archive_visio'
  post 'pads/:id/archive', to: 'pads#archive', as: 'archive_pad'

  get 'users/:id/options' => 'users#options'
  post 'users/:id/options' => 'users#set_options'
  post 'users/:id/password' => 'users#set_password'

  get 'users/:id/groups' => 'users#groups'

  get '/visios_export', to: 'visios#export', as: 'visios_export'
  get '/pads_export', to: 'pads#export', as: 'pads_export'
  get '/memos_export', to: 'memos#export', as: 'memos_export'
  get '/surveys_export', to: 'surveys#export', as: 'surveys_export'
  get '/domains_export', to: 'domains#export', as: 'domains_export'
  get '/domains/:id/users_export', to: 'domains#users_export', as: 'domain_users_export'

  resources :config_modules do
    resources :instances
  end

  root 'services#index'
  resources :services, only: %i[index show]

  get 'users/:id/alias' => 'users#alias'
  delete '/alias/delete.json' => 'users#delete_alias'
  post '/alias/create.json' => 'users#create_alias'

  get 'domains/:id/administrators' => 'domains#administrators'

  get 'domains/:id/groups', to: 'groups#index', as: 'groups'
  post 'domains/:id/groups', to: 'groups#create'
  get 'domains/:id/groups/:group_id', to: 'groups#show', as: 'group'
  delete 'domains/:id/groups/:group_id', to: 'groups#destroy'
  patch 'domains/:id/groups/:group_id', to: 'groups#update', as: 'group_update'
  post 'login' => 'users#login'
  get 'logout' => 'users#logout', as: :logout

  get 'domains/:id/resources' => 'resources#index'
  post 'domains/:id/resources' => 'resources#create'
  delete 'domains/:id/resources' => 'resources#destroy'

  get 'domains/:id/infos' => 'domain_infos#index'
  get 'domains/:id/infos/:mod_id' => 'domain_infos#new'
  post 'domains/:id/infos/:mod_id' => 'domain_infos#create'

  get 'domains/:id/details' => 'domain_details#edit'
  post 'domains/:id/details' => 'domain_details#update'

  get 'visios' => 'visios#index'
  get 'visios/:id/users' => 'visios#users'
  get 'about' => 'about#index', as: 'about'
  get 'current_user' => 'users#current_user'
  post 'visios/:id/mails' => 'visios#mails'
  delete 'visios/:id/users' => 'visios#destroy_users'

  post '/visios_groups' => 'visios_groups#create'
  delete 'visios_groups/:id' => 'visios_groups#destroy'
  post '/visios_users' => 'visios_users#create'
  delete 'visios_users/:id' => 'visios_users#destroy'

  get '/visios/:id/button_to_bbb', to: 'visios#button_to_bbb', as: 'button_to_bbb'
  get '/visios/:id/recordings', to: 'visio_recordings#index', as: 'visio_recordings'
  get '/visios/:id/recordings_list', to: 'visio_recordings#visio_recordings', as: 'visio_recordings_list'
  get 'visios/:id/recordings/after_destroy', to: 'visio_recordings#after_destroy', as: 'visio_recordings_after_destroy'
  delete 'visios/:id/recordings/:record_id' => 'visio_recordings#destroy', as: 'visio_recordings_destroy'
  get '/visios/:id/settings', to: 'visio_settings#index', as: 'visio_settings'
  post '/visios/:id/settings', to: 'visio_settings#update_setting', as: 'visio_settings_update_setting'
  post '/visios/:id/settings/generate_viewer_access_code', to: 'visio_settings#generate_viewer_access_code',
                                                           as: 'visio_settings_generate_viewer_access_code'
  post '/visios/:id/settings/generate_moderator_access_code', to: 'visio_settings#generate_moderator_access_code',
                                                              as: 'visio_settings_generate_moderator_access_code'
  get 'visios/:id/recordings/:record_id/download', to: 'visio_recordings#download', as: 'visio_recording_download'

  post '/pads_groups' => 'pads_groups#create'
  delete 'pads_groups/:id' => 'pads_groups#destroy'

  post '/pads_users' => 'pads_users#create'
  delete 'pads_users/:id' => 'pads_users#destroy'

  get 'pads/:id/invitation' => 'pads#invitation'
  post 'pads/:id/mails' => 'pads#mails'
  post 'pads/:id/sharespad' => 'pads#sharespad'
  get 'pads/:id/users' => 'pads#users'
  delete 'pads/:id/users' => 'pads#destroy_users'

  post 'tickets/:id/new_message' => 'tickets#new_message'
  post 'surveys/:id/new_message' => 'surveys#new_message'
  get 'dates' => 'dates#index'
  get 'pads' => 'pads#show'
  get 'compta' => 'compta#index'
  get 'sympa' => 'sympa#index'

  get 'config_modules/:domain_id/infos' => 'config_modules#infos'

  get 'status' => 'events#index'
  get 'status/:id' => 'events#show', as: :show_instance_status
  get 'status/:id/events/:event_id' => 'events#messages', as: :show_instance_event
  post 'status/:id/events/:event_id' => 'events#new_message', as: :new_instance_event
  patch 'status/:id/events/:event_id' => 'events#update', as: :update_instance_event
  get 'status/:id/new' => 'events#new', as: :new_event
  post 'status/:id/new' => 'events#create', as: :create_instance_event

  post 'surveys/:id/share' => 'surveys#share'

  get 'statistics' => 'statistics#index'
  get 'statistics/instances' => 'statistics#instances'

  get '/invitations/:tag/:id', to: 'invitations#index', as: 'invitations'

  get 'forms/:id/formlines' => 'formlines#index'
  post '/forms/:id/formlines/new' => 'formlines#new'

  post '/invitations/:tag/:id/invite' => 'invitations#invite'
  get '/invitation/destroy/:type_id' => 'invitations#destroy'
  get '/invitation/send_email/:type_id' => 'invitations#share_invitation_to_email'
  get 'import' => 'import#launch_import'
  get 'end_visio', to: 'external_pages#end_visio', as: 'end_visio'
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :survey_options, dependent: :destroy
  has_many :invitation_groups
  has_many :invitation_users
  has_many :messages
  before_destroy :delete_invitations, :delete_messages

  def number_participant
    options_survey = SurveyOption.where(survey_id: id).distinct
    number_participant = 0
    options_survey.each do |opt|
      number_participant += SurveyAnswer.where(survey_option_id: opt.id).distinct.count
    end
    number_participant
  end

  def invitation_users
    InvitationUser.where(module_tag: 'survey', module_id: id)
  end

  def invitation_groups
    InvitationGroup.where(module_tag: 'survey', module_id: id)
  end

  def messages
    Message.where(module_tag: 'survey', module_id: id)
  end

  def delete_invitations
    invitation_users.destroy_all
    invitation_groups.destroy_all
  end

  def delete_messages
    messages.destroy_all
  end

  def already_participated(uuid)
    options_survey = SurveyOption.where(survey_id: id).distinct
    SurveyAnswer.where(uuid:, survey_option_id: options_survey.ids).distinct.first
  end

  def name
    question
  end

  def owner
    User.find(owner_id)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[show edit update destroy share new_message]
  before_action except: %i[show new_message] do
    only_authorized_users('Survey')
  end
  before_action :set_dataset, only: %i[index export]
  before_action :super_admin_only, only: %i[edit update]
  before_action :set_owner_survey, only: %i[destroy share invite_users invite_groups invite_emails]
  before_action only: %i[edit update destroy] do
    only_owner!(@survey.owner_id, surveys_path)
  end

  # GET /surveys
  # GET /surveys.json
  def index; end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    survey_options = SurveyOption.where(survey_id: @survey.id)
    @token = params[:token]
    @uuid = if @current_user
              @current_user.id
            elsif @token
              @token
            end
    has_invite = InvitationUser.where(module_id: @survey.id, module_tag: 'survey', uuid: @uuid)
    unless @survey.owner_id.eql?(@uuid) || has_invite&.count&.positive?
      redirect_to services_url, notice: (I18n.t 'modules.survey.noticeinvite').to_s
    end
    # @has_answered = SurveyAnswer.joins(:survey_option)
    # .where('survey_options.survey_id=? and uuid=?', @survey.id, @uuid)
    # .count.positive?

    awnsers = SurveyAnswer.joins(:survey_option)
                          .where('survey_options.survey_id': @survey.id)
    participants = awnsers.collect do |awnser|
      if awnser[:uuid].include?(UUID_FOR_EXTERNAL_SURVEY)

        user =  InvitationUser.where(module_id: @survey.id, module_tag: 'survey', uuid: awnser[:uuid]).first
        { uuid: awnser[:uuid], name: user.email, internal: false }
      else
        user = User.find(awnser[:uuid])
        { uuid: awnser[:uuid], name: user.name, internal: true }
      end
    end.uniq

    options = SurveyOption.where(survey_id: @survey.id)
    @answers_table = [options.collect { |option| option[:choice] }.unshift(nil)]
    participants.each do |participant|
      reponses = [participant[:name]]
      options.each do |option|
        reponses << SurveyAnswer.where(survey_option_id: option.id, uuid: participant[:uuid])
                                .count.positive?
      end
      @answers_table << reponses
    end

    @options = []
    max_answers = 0
    survey_options.each do |option|
      answers = SurveyAnswer.where(survey_option_id: option.id)
      max_answers = answers.count if answers.count > max_answers
      opt = { id: option.id, choice: option.choice, count: answers.count, users: [] }
      answers.each do |answer|
        user = User.find(answer.uuid)

        opt[:users] << if answer.uuid.start_with?(UUID_FOR_EXTERNAL_SURVEY)
                         ext_user = InvitationUser.where(module_id: @survey.id, module_tag: 'survey',
                                                         uuid: answer.uuid).first
                         { email: ext_user.email }
                       else
                         { name: user.name, id: user.id, me: (@uuid == user.id) }
                       end
      end
      @options << opt
    end
    max_answers = -1 if max_answers.zero?
    @options.each do |option|
      option[:best_choice] = max_answers == option[:count]
    end
    log_statistics('Survey', 'Survey')

    @user = if current_user
              current_user.name
            else
              InvitationUser.where(module_id: @survey.id, module_tag: 'survey',
                                   uuid: @uuid).first&.email
            end
    @list_messages = Message.where(module_id: @survey.id, module_tag: 'survey').order('created_at DESC')
    @message = Message.new
    @module_tag = 'surveys'
    @module_id = @survey.id
    @url_message = @token ? "/#{@module_tag}/#{@module_id}/new_message?token=#{@token}" : "/#{@module_tag}/#{@module_id}/new_message"

    logger.debug "Answers: #{@answers_table}"
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
    @survey.end_date = DateTime.now + 1.week
  end

  # POST /surveys/1/share
  def share
    remove_users # Remove emails also
    remove_groups

    total1, errors1 = invite_users
    total2, errors2 = invite_groups
    total3, errors3 = invite_emails

    total = total1 + total2 + total3
    errors = errors1 + errors2 + errors3
    respond_to do |format|
      format.html do
        if errors.positive?
          redirect_to surveys_url,
                      errors: "Survey could not send emails to #{errors}/#{total}."
        else
          redirect_to surveys_url,
                      notice: "Survey successfully send #{total} emails."
        end
      end
      format.json do
        head :no_content
      end
    end
  end

  # GET /surveys/1/edit
  def edit; end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)
    @survey.owner_id = @current_user.id
    @survey.uuid = random_uuid

    @survey.end_date = DateTime.strptime(survey_params[:end_date], '%Y-%m-%dT%H:%M')

    options_list = params[:options].nil? ? [] : JSON.parse(params[:options])

    if @survey.end_date < DateTime.now
      redirect_to surveys_url, alert: (I18n.t 'modules.survey.noticeendate').to_s
      return
    end

    if options_list.count < 2
      redirect_to surveys_url, alert: (I18n.t 'modules.survey.noticeoptions').to_s
      return
    end

    if @survey.save
      options_list.each do |o|
        logger.debug "Option: #{o}  "
        option = SurveyOption.new
        option.choice = o
        option.survey_id = @survey.id
        option.save
      end
      redirect_to surveys_path, notice: (I18n.t 'modules.survey.noticecreate').to_s
    else
      render :new
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update; end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    if @survey.destroy
      redirect_to surveys_url, notice: (I18n.t 'modules.survey.noticedestroy').to_s
    else
      redirect_to surveys_url, alert: 'Error'
    end
  end

  def new_message
    @token = params[:token]
    @uuid = if @current_user
              @current_user.id
            elsif @token
              @token
            end

    message = Message.new(user_id: @uuid, module_id: @survey.id, module_tag: 'survey',
                          message: params[:message][:message])

    if message.save
      redirect_to survey_path(token: @token)
    else
      render :new
    end
  end

  def export
    send_data generate_csv(@dataset),
              type: 'text/csv; charset=utf-8; header=present',
              disposition: 'attachment; filename=surveys.csv'
  end

  private

  def set_dataset
    archived = params[:archived] == '1'
    now = DateTime.now

    id_survey_invite = InvitationUser.where(module_tag: 'survey', uuid: @current_user.id).distinct.collect(&:module_id)
    id_survey_invite += InvitationGroup.where(module_tag: 'survey',
                                              group_id: @current_user.groups_uuid).distinct.collect(&:module_id)
    surveys = Survey.where('owner_id = ? or id in (?) ', @current_user.id, id_survey_invite)
                    .where("end_date #{archived ? '<' : '>='} ?", now)

    @authors = authors_from_surveys(surveys)

    surveys = surveys_filters_and_order(surveys, index_params)
    @dataset = dataset_pagination(surveys, index_params)
  end

  def generate_csv(dataset)
    CSV.generate do |csv|
      csv << [I18n.t('modules.survey.titlesurvey'),
              I18n.t('modules.survey.descripsurvey'),
              I18n.t('modules.survey.creatorsurvey'),
              I18n.t('modules.survey.enddatesurvey'),
              I18n.t('modules.survey.anonymous_title')]

      dataset[:items].each do |data|
        csv << [data.question,
                data.comment,
                data.owner&.name,
                data.end_date,
                data.anonymous]
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_survey
    @survey = Survey.find(params[:id])
  end

  def set_owner_survey
    return unless @survey.owner_id != @current_user.id

    redirect_to '/surveys', notice: (I18n.t 'modules.survey.noticenotdestroy').to_s
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def survey_params
    params.require(:survey).permit(:end_date, :question, :comment, :allow_multiple, :anonymous)
  end

  def index_params
    params.permit(:author, :order, :query, :page, :items_per_page, :archived)
  end

  def authors_from_surveys(surveys)
    authors = surveys.collect { |p| [p.owner&.name, p.owner_id] if p.owner }
    authors.uniq.compact
  end

  def surveys_filters_and_order(surveys, params)
    surveys = surveys.where(owner_id: params[:author]) if params[:author].present?

    if params[:query].present?
      surveys = surveys.where('question ILIKE ? or comment ILIKE ?',
                              "%#{params[:query]}%",
                              "%#{params[:query]}%")
    end

    if params[:order]&.present?
      order_column, order_direction = params[:order].split(',')
      order_direction = 'DESC' unless %w[ASC DESC].include?(order_direction)
    else
      order_column = 'end_date'
      order_direction = 'DESC'
    end

    surveys.order("#{order_column} #{order_direction}")
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper 
end

app/views/surveys/_form.html.erb
<div class="flex justify-between m-10">
  <div class='hidden lg:flex w-1/4'></div>
  <div class="w-full xl:w-1/2">
    <%= form_for(@survey) do |form| %>
      <% if @survey.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize( @survey.errors.count, "error" ) %> prohibited this survey from being saved:
          </h2>
          <ul>
            <% @survey.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="flex flex-col gap-8 ">
        <div class="flex flex-col md:flex-row gap-8">
          <div class="flex flex-col gap-8">
            <div class="flex flex-col gap-2">
              <%= build_text_field(form, 'question', I18n.t('modules.survey.titlesurvey'), 'pencil-alt', required: true) %>
              <%= build_text_area(form, 'comment', 'align-left', placeholder: I18n.t('modules.survey.descripsurvey')) %>
              <%= build_datetime_field('survey', 'end_date', @survey.end_date, 'calendar', required: true) %>
            </div>

            <div class="flex flex-col gap-2">
              <%= build_toggle_field(form, "allow_multiple", ts('modules.survey.toallowmanychoice')) %>
              <%= build_toggle_field(form, "anonymous", ts('modules.survey.anonymous')) %>
            </div>
          </div>

          <div class="flex flex-col gap-2">
            <div x-data="{
            choices: [],
            choices_json: '',
            newChoice: '',
            addChoice() {
              if (this.newChoice && !this.choices.includes(this.newChoice)) {
                this.choices.push(this.newChoice);
                this.newChoice = '';
                this.choices_json = JSON.stringify(this.choices)
              }
            },
            deleteChoice(index) {
              this.choices.splice(index, 1);
              this.choices_json = JSON.stringify(this.choices)
            },
          }">

              <div class="relative overflow-x-auto">
                <table x-show="choices.length > 0" class="w-full text-sm text-black ">
                  <thead class="text-sm text-white uppercase bg-zourit-1">
                    <tr>
                      <th scope="col" class="px-6 py-3 rounded-l-lg">
                        <%= t('modules.survey.choice_index') %>
                      </th>
                      <th scope="col" class=" px-6 py-3">
                        <%= t('modules.survey.optionsurvey') %>
                      </th>
                      <th scope="col" class=" px-6 py-3 rounded-r-lg">

                      </th>
                    </tr>
                  </thead>
                  <tbody class="items-center">
                    <template x-for="(choice, index) in choices" :key="choice">
                      <tr class="border-b border-gray-200 hover:bg-gray-100 dark:bg-white hover:dark:bg-gray-200 ">
                        <td class="px-4 py-2 whitespace-nowrap">
                          <span x-text="index + 1"></span>
                        </td>
                        <td class="px-4 py-2 whitespace-nowrap" >
                          <span x-text="choice"></span>
                        </td>
                        <td>
                          <button @click="deleteChoice(index)">
                            <%= fa_icon('trash') %>
                          </button>
                        </td>
                      </tr>
                    </template>
                  </tbody>
                </table>
              </div>

              <input type="text" name="options" id="survey_options" required="required" x-model="choices_json" class="hidden">

              <div class="flex flex-col gap-2">
                <div class="flex flex-row">
                  <span class="h-auto rounded-l-lg bg-zourit-1 text-gray-100 p-2"><%= ts('modules.survey.choicesurvey') %></span>
                  <input type="text" name="" id="newChoice" x-model="newChoice" value="" placeholder="<%= ts('modules.survey.obligation') %>" class="bg-gray-100 border border-gray-800 text-gray-800 text-sm rounded-r-lg w-full pl-5 p-2 focus:border-zourit-1 focus:ring-1 focus:ring-zourit-1">
                </div>

                <button @click="addChoice()" type="button" class="text-white bg-zourit-1 hover:bg-zourit-2 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2"><%= ts('modules.survey.addoption') %></button>
              </div>
            </div>
          </div>
        </div>

        <div class="flex flex-row justify-center gap-2">
          <%= button_tag I18n.t('modules.survey.valid'),
        class: "rounded-lg bg-zourit-1 text-gray-100 hover:text-gray-100 hover:bg-gray-800 text-sm px-5 py-2" %>
          <%= link_to I18n.t('modules.survey.annuler') , surveys_path,
      class: "rounded-lg bg-gray-100 text-gray-800 hover:text-gray-100 hover:bg-gray-800 text-sm px-5 py-2" %>
        </div>
      </div>
    <% end %>

  </div>
  <div class='hidden xl:flex w-1/4'></div>
</div>

app/views/surveys/_survey.html.erb
<tr id="<%= dom_id survey %>" class="text-sm even:bg-gray-100 dark:even:bg-gray-900 dark:text-gray-200">
  <td class="pl-5 py-3 px-2">
    <% owner = (survey.owner_id == @current_user.id) %>
    <i class="fa<%= 'r' unless owner %> fa-star"
            data-toggle='tooltip' data-placement='bottom'>
    </i>
  </td>
  <td class="text-zourit-1 hover:text-gray-800 hover:dark:text-white px-2 w-full sm:w-1/4">
    <%= link_to survey.question, survey, title: survey.question, class: "font-bold", data: { toggle: 'tooltip', placement: 'bottom', turbo: false } %>
  </td>
  <td class="px-2 hidden lg:table-cell w-full">
    <%= "#{survey.comment.to_s[0..100]} #{'...' if survey.comment.to_s.length>100}" %>
  </td>
  <% user = User.find(survey.owner_id) %>
  <td class="px-2 lg:whitespace-nowrap hidden sm:table-cell"><%= "#{user&.first_name} #{user&.last_name}" %></td>
  <td class="px-2 hidden md:table-cell lg:whitespace-nowrap"><%= survey.end_date.strftime("%d/%m/%Y %H:%M %Z") %></td>
  <td class="pl-5 py-3 px-2 hidden lg:table-cell">
    <% if survey.anonymous %>
      <%= fa_icon('check') %>
    <% else %>
      <%= fa_icon('times') %>
    <% end %>
  </td>
  <td class="">
    <div class="flex flex-row flex-nowrap mr-2 ">
      <%= link_to survey, title: ts('modules.survey.accesstosurvey'), class: "mr-2 rounded-lg text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm", data: { toggle: 'tooltip', placement: 'bottom', turbo: false } do %>
        <%= fa_icon('eye') %>
      <% end %>
      <% if !@archive && owner %>
        <%= link_to "/invitations/surveys/#{survey.id}", title: ts('modules.survey.sharesurvey'), class: "rounded-l-lg text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm", data: { toggle: 'tooltip', placement: 'bottom', turbo: false } do %>
          <%= fa_icon('users') %>
        <% end %>
      <% end %>
      <% if owner %>
        <%= link_to survey, method: :delete, title: ts('modules.survey.deletesurvey'), class: "rounded-r-lg text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm", data: { "turbo-method": :delete, turbo_confirm: "#{ts 'modules.survey.deleteconfirmation  '}"} do %>
          <%= fa_icon('trash') %>
        <% end %>
      <% end %>
    </div>
  </td>
</tr>

app/views/surveys/_surveys.html.erb
<%= turbo_frame_tag "surveys", target: "_top" do %>
  <div class="inline-block min-w-full align-middle pt-2">
    <table class="min-w-full divide-y divide-gray-300">
      <thead>
        <tr class="whitespace-nowrap text-md text-left font-semibold text-gray-400 bg-gray-800 dark:bg-gray-200 dark:text-gray-600">
          <th scope="col" class="py-5"></th>
          <th scope="col" class="pl-2"><%= build_th_order('question', ts('modules.survey.titlesurvey'),params[:order]) %></th>
          <th scope="col" class="pl-2 hidden lg:table-cell"><%= ts 'modules.survey.descripsurvey' %></th>
          <th scope="col" class="pl-2 hidden sm:table-cell"><%= ts 'modules.survey.creatorsurvey' %></th>
          <th scope="col" class="pl-2 hidden md:table-cell whitespace-nowrap"><%= build_th_order('end_date', ts('modules.survey.enddatesurvey'), params[:order]) %></th>
          <th scope="col" class="pl-2 hidden md:table-cell whitespace-nowrap"><%= build_th_order('anonymous', ts('modules.survey.anonymous_title'), params[:order]) %></th>
          <th scope="col" class=""></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
        <%= render @dataset[:items] %>
      </tbody>
    </table>
  </div>
  <div class="text-sm text-gray-500 mt-5">
    <%= render "application/pagination", dataset: @dataset do %>
      <%= link_to surveys_export_path(author: params[:author], 
                                      order: params[:order], 
                                      query: params[:query], 
                                      page: 1, 
                                      items_per_page: @dataset[:count], 
                                      archived: params[:archived]), 
                                      class: "ml-2 rounded-lg bg-zourit-1 hover:bg-gray-800 !text-gray-100 hover:text-gray-100 text-lg p-2", title: "Tout exporter" do %>
        <%= fa_icon('download') %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/surveys/new.html.erb
<%= render partial:'application/page_title', locals: {title: t('modules.survey.addsurvey'), icon: icon('Survey'), back: {url: surveys_path, title: t('modules.survey.title')} } %>

<%= render 'form' %>