config/routes.rb
Rails.application.routes.draw do
  resources :domain_categories
  resources :forms do
    resources :formlines
  end
  resources :memos
  resources :links, except: %i[show]
  resources :survey_users
  resources :survey_groups
  resources :survey_answers
  resources :survey_options
  resources :surveys
  resources :instance_stories
  resources :instance_states
  resources :tickets
  resources :ticket_categories
  resources :ticket_statuses

  resources :pads_users
  resources :pads_groups
  resources :pads
  resources :visios
  resources :domains
  resources :users

  post 'domains/:id/users/:user_id', to: 'domains#update_user'
  get 'domains/:id/users/:user_id/edit', to: 'domains#edit_user', as: 'edit_domain_user'
  get 'domains/:id/users/new', to: 'domains#new_user', as: 'new_domain_user'
  post 'domains/:id/users', to: 'domains#create_user'
  delete 'domains/:id/users/:user_id', to: 'domains#delete_user', as: 'delete_domain_user'

  post 'memos/:id/archive', to: 'memos#archive', as: 'archive_memo'
  post 'visios/:id/archive', to: 'visios#archive', as: 'archive_visio'
  post 'pads/:id/archive', to: 'pads#archive', as: 'archive_pad'

  get 'users/:id/options' => 'users#options'
  post 'users/:id/options' => 'users#set_options'
  post 'users/:id/password' => 'users#set_password'

  get 'users/:id/groups' => 'users#groups'

  get '/visios_export', to: 'visios#export', as: 'visios_export'
  get '/pads_export', to: 'pads#export', as: 'pads_export'
  get '/memos_export', to: 'memos#export', as: 'memos_export'
  get '/surveys_export', to: 'surveys#export', as: 'surveys_export'
  get '/domains_export', to: 'domains#export', as: 'domains_export'
  get '/domains/:id/users_export', to: 'domains#users_export', as: 'domain_users_export'

  resources :config_modules do
    resources :instances
  end

  root 'services#index'
  resources :services, only: %i[index show]

  get 'users/:id/alias' => 'users#alias'
  delete '/alias/delete.json' => 'users#delete_alias'
  post '/alias/create.json' => 'users#create_alias'

  get 'domains/:id/administrators' => 'domains#administrators'

  get 'domains/:id/groups', to: 'groups#index', as: 'groups'
  post 'domains/:id/groups', to: 'groups#create'
  get 'domains/:id/groups/:group_id', to: 'groups#show', as: 'group'
  delete 'domains/:id/groups/:group_id', to: 'groups#destroy'
  patch 'domains/:id/groups/:group_id', to: 'groups#update', as: 'group_update'
  post 'login' => 'users#login'
  get 'logout' => 'users#logout', as: :logout

  get 'domains/:id/resources' => 'resources#index'
  post 'domains/:id/resources' => 'resources#create'
  delete 'domains/:id/resources' => 'resources#destroy'

  get 'domains/:id/infos' => 'domain_infos#index'
  get 'domains/:id/infos/:mod_id' => 'domain_infos#new'
  post 'domains/:id/infos/:mod_id' => 'domain_infos#create'

  get 'domains/:id/details' => 'domain_details#edit'
  post 'domains/:id/details' => 'domain_details#update'

  get 'visios' => 'visios#index'
  get 'visios/:id/users' => 'visios#users'
  get 'about' => 'about#index', as: 'about'
  get 'current_user' => 'users#current_user'
  post 'visios/:id/mails' => 'visios#mails'
  delete 'visios/:id/users' => 'visios#destroy_users'

  post '/visios_groups' => 'visios_groups#create'
  delete 'visios_groups/:id' => 'visios_groups#destroy'
  post '/visios_users' => 'visios_users#create'
  delete 'visios_users/:id' => 'visios_users#destroy'

  get '/visios/:id/button_to_bbb', to: 'visios#button_to_bbb', as: 'button_to_bbb'
  get '/visios/:id/recordings', to: 'visio_recordings#index', as: 'visio_recordings'
  get '/visios/:id/recordings_list', to: 'visio_recordings#visio_recordings', as: 'visio_recordings_list'
  get 'visios/:id/recordings/after_destroy', to: 'visio_recordings#after_destroy', as: 'visio_recordings_after_destroy'
  delete 'visios/:id/recordings/:record_id' => 'visio_recordings#destroy', as: 'visio_recordings_destroy'
  get '/visios/:id/settings', to: 'visio_settings#index', as: 'visio_settings'
  post '/visios/:id/settings', to: 'visio_settings#update_setting', as: 'visio_settings_update_setting'
  post '/visios/:id/settings/generate_viewer_access_code', to: 'visio_settings#generate_viewer_access_code',
                                                           as: 'visio_settings_generate_viewer_access_code'
  post '/visios/:id/settings/generate_moderator_access_code', to: 'visio_settings#generate_moderator_access_code',
                                                              as: 'visio_settings_generate_moderator_access_code'
  get 'visios/:id/recordings/:record_id/download', to: 'visio_recordings#download', as: 'visio_recording_download'

  post '/pads_groups' => 'pads_groups#create'
  delete 'pads_groups/:id' => 'pads_groups#destroy'

  post '/pads_users' => 'pads_users#create'
  delete 'pads_users/:id' => 'pads_users#destroy'

  get 'pads/:id/invitation' => 'pads#invitation'
  post 'pads/:id/mails' => 'pads#mails'
  post 'pads/:id/sharespad' => 'pads#sharespad'
  get 'pads/:id/users' => 'pads#users'
  delete 'pads/:id/users' => 'pads#destroy_users'

  post 'tickets/:id/new_message' => 'tickets#new_message'
  post 'surveys/:id/new_message' => 'surveys#new_message'
  get 'dates' => 'dates#index'
  get 'pads' => 'pads#show'
  get 'compta' => 'compta#index'
  get 'sympa' => 'sympa#index'

  get 'config_modules/:domain_id/infos' => 'config_modules#infos'

  get 'status' => 'events#index'
  get 'status/:id' => 'events#show', as: :show_instance_status
  get 'status/:id/events/:event_id' => 'events#messages', as: :show_instance_event
  post 'status/:id/events/:event_id' => 'events#new_message', as: :new_instance_event
  patch 'status/:id/events/:event_id' => 'events#update', as: :update_instance_event
  get 'status/:id/new' => 'events#new', as: :new_event
  post 'status/:id/new' => 'events#create', as: :create_instance_event

  post 'surveys/:id/share' => 'surveys#share'

  get 'statistics' => 'statistics#index'
  get 'statistics/instances' => 'statistics#instances'

  get '/invitations/:tag/:id', to: 'invitations#index', as: 'invitations'

  get 'forms/:id/formlines' => 'formlines#index'
  post '/forms/:id/formlines/new' => 'formlines#new'

  post '/invitations/:tag/:id/invite' => 'invitations#invite'
  get '/invitation/destroy/:type_id' => 'invitations#destroy'
  get '/invitation/send_email/:type_id' => 'invitations#share_invitation_to_email'
  get 'import' => 'import#launch_import'
  get 'end_visio', to: 'external_pages#end_visio', as: 'end_visio'
end

app/models/memo.rb
class Memo < ApplicationRecord
  has_many :invitation_groups
  has_many :invitation_users
  has_many :memo_archives, dependent: :destroy
  before_destroy :delete_invitations

  def invitation_users
    InvitationUser.where(module_tag: 'memo', module_id: id)
  end

  def invitation_groups
    InvitationGroup.where(module_tag: 'memo', module_id: id)
  end

  def delete_invitations
    invitation_users.destroy_all
    invitation_groups.destroy_all
  end

  def owner
    User.find(owner_id)
  end

  def external_url(domain)
    mod = ConfigModule.where(name: 'Framemo').first
    url_server = mod.instance_for_domain(domain).option_by_name('url')
    url_embedded = url_server
    url_embedded += '/' unless url_server[-1] == '/'
    url_embedded += uuid

    url_embedded
  end

  def archived?(user)
    memo_archives.where(user_id: user.id).count.positive?
  end

  def archive(user)
    MemoArchive.where(memo_id: id, user_id: user.id).first_or_create
  end

  def unarchive(user)
    memo_archives.where(user_id: user.id).destroy_all
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action do
    only_authorized_users('Framemo')
  end
  before_action :set_dataset, only: %i[index export]
  before_action :set_memo, only: %i[show edit update destroy archive]
  before_action only: %i[edit update destroy] do
    only_owner!(@memo.owner_id, memos_path)
  end

  # GET /memos
  def index; end

  # GET /memos/1
  def show
    @type_page = 'iframe'
    is_owner = (@memo.owner_id == @current_user.id)
    user_invitation = InvitationUser.where(module_id: @memo.id, module_tag: 'memo',
                                           uuid: @current_user.id).count.positive?
    group_invitation = InvitationGroup.where(module_id: @memo.id, module_tag: 'memo',
                                             group_id: @current_user.groups_uuid).count.positive?
    unless is_owner || user_invitation || group_invitation
      redirect_to memos_path, notice: (I18n.t 'modules.framemo.noparticipe')
    end
    configmodule = ConfigModule.where(name: configmodule_name(Core::Framemo)).first
    domain_info = DomainInfo.where(domain_id: current_user.domain.id, config_module_id: configmodule.id).first
    url_server = domain_info.instance.option_by_name('url')
    if url_server
      @url_embedded = url_server
      @url_embedded += '/' unless @url_embedded[-1] == '/'
      @url_embedded += @memo.uuid
      log_statistics(configmodule.name, domain_info.instance.name)
    else
      redirect_to services_path, notice: (I18n.t 'modules.framemo.noactif').to_s
    end
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit; end

  # POST /memos
  def create
    @memo = Memo.new(memo_params)
    @memo.uuid = random_uuid
    @memo.owner_id = @current_user.id

    if @memo.save
      redirect_to @memo, notice: I18n.t('modules.framemo.noticecreate', memo_name: @memo.name).to_s
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /memos/1
  def update
    if @memo.update(memo_params)
      redirect_to memos_path, notice: I18n.t('modules.framemo.noticeupdate', memo_name: @memo.name).to_s
    else
      render :edit
    end
  end

  # DELETE /memos/1
  def destroy
    @memo.destroy
    redirect_to memos_url, notice: I18n.t('modules.framemo.verif').to_s
  end

  # POST /memos/1/archive
  def archive
    @memo.archived?(@current_user) ? @memo.unarchive(@current_user) : @memo.archive(@current_user)
    redirect_to memos_url
  end

  def export
    send_data generate_csv(@dataset),
              type: 'text/csv; charset=utf-8; header=present',
              disposition: 'attachment; filename=memos.csv'
  end

  private

  def set_dataset
    id_memo_invite = InvitationUser.where(module_tag: 'memo',
                                          uuid: @current_user.id).distinct.collect(&:module_id)
    id_memo_invite += InvitationGroup.where(module_tag: 'memo',
                                            group_id: @current_user.groups_uuid).distinct.collect(&:module_id)

    memos_all = Memo.where('owner_id = ? or memos.id in (?)', @current_user.id,
                           id_memo_invite).distinct
    memos = if index_params[:archived] == '1'
              memos_all.joins(:memo_archives)
                       .where('memo_archives.user_id = ?', @current_user.id)
                       .distinct.to_a
            else
              memos_all.reject { |memo| memo.archived?(@current_user) }
            end

    @authors = authors_from_memos(memos_all)

    memos = memos_filters_and_order(memos, index_params)
    @dataset = dataset_pagination(memos, index_params)
  end

  def generate_csv(dataset)
    CSV.generate do |csv|
      csv << [t('modules.framemo.memoname'),
              t('modules.framemo.memodesc'),
              t('modules.framemo.author'),
              t('modules.framemo.createdate')]

      dataset[:items].each do |data|
        csv << [
          data.name,
          data.comment,
          data.owner&.name,
          data.created_at
        ]
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_memo
    @memo = Memo.find(params[:id])
  rescue StandardError => e
    flash.alert = "#{I18n.t('modules.framemo.dontexist')}|#{e}"
    redirect_to memos_path, index_params
  else
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def memo_params
    params.require(:memo).permit(:name, :comment, :uuid, :owner_id)
  end

  def index_params
    params.permit(:author, :order, :query, :page, :items_per_page, :archived)
  end

  def authors_from_memos(memos)
    authors = memos.collect { |memo| [memo.owner&.name, memo.owner_id] if memo.owner }
    authors.uniq.compact
  end

  def memos_filters_and_order(memos, params)
    if params[:author].present?
      memos.select! do |memo|
        memo.owner_id == params[:author]
      end
    end

    if params[:query].present?
      memos.select! do |memo|
        memo.name.downcase.include?(params[:query].downcase) or memo.comment.downcase.include?(params[:query].downcase)
      end
    end

    if params[:order].to_s.empty?
      memos.sort! { |a, b| b.created_at <=> a.created_at }
    else
      order_column, order_direction = params[:order].split(',')
      order_column = 'name' unless %w[name created_at].include?(order_column)
      order_direction = 'DESC' unless %w[ASC DESC].include?(order_direction)
      if order_column == 'name'
        memos.sort! { |a, b| b.name.downcase <=> a.name.downcase } if order_direction == 'ASC'
        memos.sort! { |a, b| a.name.downcase <=> b.name.downcase } if order_direction == 'DESC'
      else
        if order_direction == 'ASC'
          memos.sort! do |a, b|
            b.created_at <=> a.created_at
          end
        end
        if order_direction == 'DESC'
          memos.sort! do |a, b|
            a.created_at <=> b.created_at
          end
        end
      end
    end

    memos
  end
end

app/views/memos/_form.html.erb
<div class="flex justify-between m-10">
  <div class='hidden lg:flex'></div>
  <div class="w-full lg:w-1/2">
    <%= form_for(@memo) do |f| %>
      <% if @memo.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize( @memo.errors.count, "error" ) %> prohibited this memo from being saved:
          </h2>
          <ul>
            <% @memo.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="flex flex-col gap-2">
        <%= build_text_field(f, 'name', I18n.t('modules.framemo.memoname'), 'pencil-alt') %>
        <%= build_text_area(f, 'comment', 'align-left', placeholder: I18n.t('modules.framemo.memodesc')) %>
        <div class="flex flex-row justify-center gap-2">
          <%= button_tag I18n.t('modules.framemo.valid'),
        class: "rounded-lg bg-zourit-1 text-gray-100 hover:text-gray-100 hover:bg-gray-800 text-sm px-5 py-2" %>
          <%= link_to I18n.t('modules.framemo.annuler') , memos_path,
        class: "rounded-lg bg-gray-100 text-gray-800 hover:text-gray-100 hover:bg-gray-800 text-sm px-5 py-2" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class='hidden lg:flex'></div>
</div>

app/views/memos/_memo.html.erb
<tr id="<%= dom_id memo %>" class="text-sm even:bg-gray-100 dark:even:bg-gray-900 dark:text-gray-200">
  <td class="pl-5 py-3 px-2">
    <% owner = (memo.owner_id == @current_user.id) %>
    <i class="fa<%= 'r' unless owner %> fa-star"
            title="<%= owner ? ts('modules.framemo.owner') : ts('modules.framemo.not_owner') %>"
            data-toggle='tooltip' data-placement='bottom'>
    </i>
  </td>
  <td class="text-zourit-1 hover:text-gray-800 hover:dark:text-white  px-2 w-1/4">
    <%= link_to memo.name, memo, title: memo.comment, class: "font-bold", data: { toggle: 'tooltip', placement: 'bottom', turbo: false } %>
  </td>
  <td class="px-2 hidden lg:table-cell w-full">
    <%= "#{memo.comment.to_s[0..100]} #{'...' if memo.comment.to_s.length>100}" %>
  </td>
  <% user = User.find(memo.owner_id) %>
  <td class="px-2 lg:whitespace-nowrap hidden sm:table-cell"><%= "#{user&.first_name} #{user&.last_name}" %></td>
  <td class="px-2 hidden md:table-cell lg:whitespace-nowrap"><%= memo.created_at.strftime("%d/%m/%Y %H:%M %Z") %></td>
  <td class="">
    <div class="flex flex-row flex-nowrap mr-2 ">
      <%= link_to memo, title: ts('modules.framemo.accesmemo_button'), class: "rounded-l-lg text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm", data: { turbo: false } do %>
        <%= fa_icon('eye') %>
      <% end %>
      <span @click="$clipboard('<%= memo.external_url(@current_user.domain) %>'); addFlashMessage('<%= t('actions.external_link_to_clipboard')%>')" 
            class="<%= "mr-2 rounded-r-lg" if params[:archived]!='1' %> text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm cursor-pointer"
            title="<%= t('actions.copy_external_link_to_clipboard') %>">
        <%= fa_icon('clipboard ') %>
      </span>
      <% if params[:archived]!='1' && owner %>
        <%= link_to edit_memo_path(memo), 
                      title: ts('modules.framemo.modifmemo_button'), 
                      class: "rounded-l-lg text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm", 
                      data: { turbo: false } do %>
          <%= fa_icon('pencil-alt') %>
        <% end %>
        <%= link_to "/invitations/memos/#{memo.id}", 
                      title: ts('modules.framemo.sharememo_button'), 
                      class: "text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm",
                      data: { turbo: false } do %>
          <%= fa_icon('users') %>
        <% end %>
      <% end %>
      <%= link_to archive_memo_path(memo.id),
                    method: :post,
                    title: params[:archived]=='1' ? ts('actions.unarchive') : ts('actions.archive'), 
                    class: "mr-2 #{ owner ? 'rounded-r-lg' : params[:archived]=='1' ? 'rounded-r-lg' : 'rounded-lg'} text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm",
                    data: { "turbo-method": :post } do %>
        <%= fa_icon('archive') %>
      <% end %>
      <% if owner %>
        <%= link_to memo, 
                    method: :delete, 
                    title: ts('modules.framemo.destroymemo_button'), 
                    class: "rounded-lg text-gray-100 hover:text-gray-100 bg-zourit-1 hover:bg-gray-800 p-2 text-sm", 
                    data: { "turbo-method": :delete, turbo_confirm: "#{ts 'modules.framemo.verif'}"} do %>
          <%= fa_icon('trash') %>
        <% end %>
      <% else %>

      <% end %>
    </div>
  </td>
</tr>

app/views/memos/_memos.html.erb
<%= turbo_frame_tag "memos", target: "_top" do %>
  <div class="inline-block min-w-full align-middle pt-2">
    <table class="min-w-full divide-y divide-gray-300">
      <thead>
        <tr class="whitespace-nowrap text-md text-left font-semibold text-gray-400 bg-gray-800 dark:bg-gray-200 dark:text-gray-600">
          <th scope="col" class="py-5"></th>
          <th scope="col" class="pl-2"><%= build_th_order('name', ts('modules.framemo.memoname'),params[:order]) %></th>
          <th scope="col" class="pl-2 hidden lg:table-cell"><%= ts 'modules.framemo.memodesc' %></th>
          <th scope="col" class="pl-2 hidden sm:table-cell"><%= ts 'modules.framemo.author' %></th>
          <th scope="col" class="pl-2 hidden md:table-cell whitespace-nowrap"><%= build_th_order('created_at', ts('modules.framemo.createdate'), params[:order]) %></th>
          <th scope="col" class=""></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
        <%= render @dataset[:items] %>
      </tbody>
    </table>
  </div>
  <div class="text-sm text-gray-500 mt-5">
    <%= render "application/pagination", dataset: @dataset do %>
      <%= link_to memos_export_path(author: params[:author], 
                                    order: params[:order], 
                                    query: params[:query], 
                                      page: 1, 
                                      items_per_page: @dataset[:count], 
                                    archived: params[:archived]), 
                                    class: "ml-2 rounded-lg bg-zourit-1 hover:bg-gray-800 !text-gray-100 hover:text-gray-100 text-lg p-2", title: "Tout exporter" do %>
        <%= fa_icon('download') %>

      <% end %>
    <% end %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<%= render partial:'application/page_title', locals: {title: t('modules.framemo.modifmemo'), icon: icon('Framemo'), back: { url: memos_path, title: t('modules.framemo.memolist') }} %>

<%= render 'form' %>

app/views/memos/index.html.erb
<%= render partial:'application/page_title', locals: {title: t('modules.framemo.memolist'), icon: icon('Framemo')} %>
<div class="flow-root text-left p-5"
  x-data="{
    refresh(page=1) {
      $refs.pageInput.value=page;
      $refs.searchForm.requestSubmit()
    }
  }">
  <%= form_with(
    url: memos_path,
    method: :get,
    class: "mb-0",
    html: { "x-ref": "searchForm" },
    data: {turbo_frame: "memos", turbo_action: "advance"}
    ) do |form| %>
    <div class="flex flex-col xl:flex-row justify-between gap-2">
      <div class='flex'>
        <%= build_button(text: ts('modules.framemo.newmemo'),
                        icon: 'plus',
                        link: new_memo_path) %>
      </div>
      <div class="flex flex-col md:flex-row gap-2">
        <div class="flex flex-row">
          <div class="h-auto rounded-l-lg bg-zourit-1 !text-gray-100 p-2 text-sm"><%= ts 'modules.framemo.author' %></div>
          <%= form.select :author, @authors, { include_blank: I18n.t('modules.framemo.all_authors') }, "@input": "refresh()", class: "pr-8 text-sm bg-gray-800 dark:bg-gray-200 text-gray-400 dark:text-gray-800 rounded-r-lg border-gray-800 focus:border-zourit-1 focus:ring-1 focus:ring-zourit-1" %>
        </div>
        <div class="flex flex-row">
          <%= button_tag id: "submit-button", class: "h-auto rounded-l-lg bg-zourit-1 hover:bg-gray-800 !text-gray-100 hover:text-gray-100 text-lg p-2" do %>
            <%= fa_icon('search') %>
          <% end %>
          <%= form.text_field :query, "@input.debounce": "refresh()", class: "bg-gray-800 dark:bg-gray-200 dark:text-gray-800 border border-gray-800 text-gray-100 text-sm rounded-r-lg w-full pl-5 p-2 focus:border-zourit-1 focus:ring-1 focus:ring-zourit-1", placeholder: "Rechercher" %>
          <!-- Ces input hidden sont modifié via alpinejs -->
          <%= form.text_field :order, 'x-ref': 'orderInput', class:"hidden" %>
          <%= form.text_field :page, 'x-ref': 'pageInput', class:"hidden" %>
        </div>
        <div class="flex items-center">
          <%= build_toggle_field(form, 
                                'archived', 
                                t('actions.archived'), 
                                checked: params[:archived] == 1, 
                                "on_change": "refresh()") %>
        </div>
      </div>
    </div>
    <div class="">
      <%= render "memos", memos: @dataset %>
    </div>
  <% end %>
</div>

app/views/memos/new.html.erb
<%= render partial:'application/page_title', locals: {title: t('modules.framemo.addmemo'), icon: icon('Framemo'), back: { url: memos_path, title: t('modules.framemo.memolist') }} %>

<%= render 'form' %>

app/views/memos/show.html.erb
<% content_for :title, @memo.name %>

<div class="zourit-iframe">
  <iframe src="<%= @url_embedded %>" width=100% frameborder="0" scrolling="yes"></iframe>
</div>